### ISSUE TITLE
왜 id를 apple로 바꿨나요?

### ISSUE THREAD

**Issue by TaehyunGong** [JongChanLee01/movie_app#1]
https://github.com/JongChanLee01/movie_app/blob/84f7d68f97f7391247a0770ca41956370865464e/public/index.html#L31

답변부탁드립니다.

**Comment by JongChanLee01** [comment]
안녕하세요 "TaehyunGong"님^^

제가 리액트를 공부를 해보고 있어서 어떤 식으로 연결이 되는지 궁금하여 id를 "root" --> "apple"로 변경을 해보았습니다!

좋은하루 보내세요~^^
감사합니다.

**Comment by TaehyunGong** [comment]
@JongChanLee01 알겠습니다.

**Comment by kimyoungjin-dev** [comment]
ㅡㅡ
